import type { ScanHistoryEntry } from '@/stores/historyStore';
import type { CheckStatus } from '@argus/shared';

/* ────────────────── JSON Export ────────────────── */
export function exportAsJSON(domain: string, checks: Map<string, CheckStatus>): void {
  const data = buildExportData(domain, checks);
  downloadFile(
    JSON.stringify(data, null, 2),
    `argus-${domain}-${formatDate()}.json`,
    'application/json',
  );
}

/* ────────────────── Markdown Export ────────────────── */
export function exportAsMarkdown(domain: string, checks: Map<string, CheckStatus>): void {
  const data = buildExportData(domain, checks);
  const lines: string[] = [];

  lines.push(`# 🔱 ARGUS Intelligence Report`);
  lines.push(`**Domain:** \`${domain}\``);
  lines.push(`**Date:** ${new Date().toISOString()}`);
  lines.push(`**Total Checks:** ${data.summary.total} | ✅ Passed: ${data.summary.passed} | ❌ Failed: ${data.summary.failed}`);
  lines.push(`**Scan Duration:** ${data.summary.duration}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const check of data.checks) {
    const icon = check.success ? '✅' : '❌';
    lines.push(`## ${icon} ${check.name}`);
    lines.push(`*Duration: ${check.duration}ms*`);
    lines.push('');

    if (check.error) {
      lines.push(`> ⚠️ Error: ${check.error}`);
      lines.push('');
      continue;
    }

    if (check.data) {
      lines.push('```json');
      lines.push(JSON.stringify(check.data, null, 2));
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by ARGUS — Web Intelligence Platform*');

  downloadFile(lines.join('\n'), `argus-${domain}-${formatDate()}.md`, 'text/markdown');
}

/* ────────────────── CSV Export (summary) ────────────────── */
export function exportAsCSV(domain: string, checks: Map<string, CheckStatus>): void {
  const rows: string[][] = [['Check ID', 'Check Name', 'Status', 'Duration (ms)', 'Error']];

  const sorted = [...checks.entries()].sort(([, a], [, b]) => a.name.localeCompare(b.name));
  for (const [id, check] of sorted) {
    rows.push([
      id,
      check.name,
      check.result?.success ? 'PASS' : 'FAIL',
      String(check.result?.duration ?? ''),
      check.result?.error ?? '',
    ]);
  }

  const csv = rows.map((r) => r.map((c) => `"${c.replace(/"/g, '""')}"`).join(',')).join('\n');
  downloadFile(csv, `argus-${domain}-${formatDate()}.csv`, 'text/csv');
}

/* ────────────────── From history entry ────────────────── */
export function exportHistoryEntry(entry: ScanHistoryEntry, format: 'json' | 'md'): void {
  if (format === 'json') {
    downloadFile(
      JSON.stringify(entry, null, 2),
      `argus-${entry.domain}-${formatDate(entry.timestamp)}.json`,
      'application/json',
    );
  } else {
    const lines: string[] = [];
    lines.push(`# 🔱 ARGUS Scan Report — ${entry.domain}`);
    lines.push(`**Date:** ${new Date(entry.timestamp).toLocaleString()}`);
    lines.push(`**Results:** ${entry.passedChecks}/${entry.totalChecks} passed | Duration: ${(entry.duration / 1000).toFixed(1)}s`);
    lines.push('');

    for (const [id, res] of Object.entries(entry.results)) {
      const icon = res.success ? '✅' : '❌';
      lines.push(`## ${icon} ${res.name}`);
      if (res.error) lines.push(`> Error: ${res.error}`);
      if (res.data) {
        lines.push('```json');
        lines.push(JSON.stringify(res.data, null, 2));
        lines.push('```');
      }
      lines.push('');
    }

    downloadFile(lines.join('\n'), `argus-${entry.domain}-${formatDate(entry.timestamp)}.md`, 'text/markdown');
  }
}

/* ────────────────── Share URL ────────────────── */
export async function copyShareUrl(domain: string): Promise<boolean> {
  const url = `${window.location.origin}/results/${encodeURIComponent(domain)}`;
  try {
    await navigator.clipboard.writeText(url);
    return true;
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = url;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
}

/* ────────────────── Helpers ────────────────── */
function buildExportData(domain: string, checks: Map<string, CheckStatus>) {
  const sorted = [...checks.entries()].sort(([, a], [, b]) => a.name.localeCompare(b.name));
  const passed = sorted.filter(([, c]) => c.result?.success).length;

  return {
    platform: 'ARGUS',
    version: '1.0.0',
    domain,
    exportedAt: new Date().toISOString(),
    summary: {
      total: sorted.length,
      passed,
      failed: sorted.length - passed,
      duration: sorted.reduce((sum, [, c]) => sum + (c.result?.duration ?? 0), 0) + 'ms',
    },
    checks: sorted.map(([id, check]) => ({
      id,
      name: check.name,
      success: check.result?.success ?? false,
      duration: check.result?.duration ?? 0,
      error: check.result?.error,
      data: check.result?.data,
    })),
  };
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function formatDate(ts?: number): string {
  const d = ts ? new Date(ts) : new Date();
  return d.toISOString().slice(0, 10);
}
